# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Launcher.ui'
#
# Created: Tue Oct 01 12:43:57 2013
#      by: PyQt4 UI code generator 4.9.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.setWindowModality(QtCore.Qt.NonModal)
        Form.resize(500, 400)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(500, 400))
        Form.setMaximumSize(QtCore.QSize(503, 400))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../data/images/icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.verticalLayout_3 = QtGui.QVBoxLayout(Form)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, -1)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.splash = QtGui.QLabel(Form)
        self.splash.setMinimumSize(QtCore.QSize(5, 0))
        self.splash.setMaximumSize(QtCore.QSize(500, 16777215))
        self.splash.setText(_fromUtf8(""))
        self.splash.setPixmap(QtGui.QPixmap(_fromUtf8("../data/images/splash.png")))
        self.splash.setObjectName(_fromUtf8("splash"))
        self.verticalLayout.addWidget(self.splash)
        self.line = QtGui.QFrame(Form)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout.addWidget(self.line)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.labelResolution = QtGui.QLabel(Form)
        self.labelResolution.setMaximumSize(QtCore.QSize(16777215, 20))
        self.labelResolution.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelResolution.setObjectName(_fromUtf8("labelResolution"))
        self.verticalLayout_2.addWidget(self.labelResolution)
        self.labelAntiAliasing = QtGui.QLabel(Form)
        self.labelAntiAliasing.setMaximumSize(QtCore.QSize(16777215, 20))
        self.labelAntiAliasing.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelAntiAliasing.setObjectName(_fromUtf8("labelAntiAliasing"))
        self.verticalLayout_2.addWidget(self.labelAntiAliasing)
        self.labelHidden_1 = QtGui.QLabel(Form)
        self.labelHidden_1.setMaximumSize(QtCore.QSize(16777215, 23))
        self.labelHidden_1.setText(_fromUtf8(""))
        self.labelHidden_1.setObjectName(_fromUtf8("labelHidden_1"))
        self.verticalLayout_2.addWidget(self.labelHidden_1)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.resolution = QtGui.QComboBox(Form)
        self.resolution.setMinimumSize(QtCore.QSize(0, 20))
        self.resolution.setObjectName(_fromUtf8("resolution"))
        self.verticalLayout_5.addWidget(self.resolution)
        self.antiAliasing = QtGui.QComboBox(Form)
        self.antiAliasing.setMinimumSize(QtCore.QSize(0, 20))
        self.antiAliasing.setObjectName(_fromUtf8("antiAliasing"))
        self.antiAliasing.addItem(_fromUtf8(""))
        self.antiAliasing.addItem(_fromUtf8(""))
        self.antiAliasing.addItem(_fromUtf8(""))
        self.antiAliasing.addItem(_fromUtf8(""))
        self.antiAliasing.addItem(_fromUtf8(""))
        self.verticalLayout_5.addWidget(self.antiAliasing)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.playButton = QtGui.QPushButton(Form)
        self.playButton.setMinimumSize(QtCore.QSize(0, 0))
        self.playButton.setMaximumSize(QtCore.QSize(16777215, 23))
        self.playButton.setObjectName(_fromUtf8("playButton"))
        self.horizontalLayout.addWidget(self.playButton)
        self.quitButton = QtGui.QPushButton(Form)
        self.quitButton.setObjectName(_fromUtf8("quitButton"))
        self.horizontalLayout.addWidget(self.quitButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.horizontalLayout_3.addLayout(self.verticalLayout_5)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.fullscreen = QtGui.QCheckBox(Form)
        self.fullscreen.setMinimumSize(QtCore.QSize(0, 20))
        self.fullscreen.setMaximumSize(QtCore.QSize(16777215, 20))
        self.fullscreen.setObjectName(_fromUtf8("fullscreen"))
        self.verticalLayout_4.addWidget(self.fullscreen)
        self.labelHidden_2 = QtGui.QLabel(Form)
        self.labelHidden_2.setMaximumSize(QtCore.QSize(16777215, 23))
        self.labelHidden_2.setText(_fromUtf8(""))
        self.labelHidden_2.setObjectName(_fromUtf8("labelHidden_2"))
        self.verticalLayout_4.addWidget(self.labelHidden_2)
        self.labelHidden_3 = QtGui.QLabel(Form)
        self.labelHidden_3.setMaximumSize(QtCore.QSize(16777215, 23))
        self.labelHidden_3.setText(_fromUtf8(""))
        self.labelHidden_3.setObjectName(_fromUtf8("labelHidden_3"))
        self.verticalLayout_4.addWidget(self.labelHidden_3)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "BGE Launcher", None, QtGui.QApplication.UnicodeUTF8))
        self.labelResolution.setText(QtGui.QApplication.translate("Form", "Resolution", None, QtGui.QApplication.UnicodeUTF8))
        self.labelAntiAliasing.setText(QtGui.QApplication.translate("Form", "Anti-Aliasing", None, QtGui.QApplication.UnicodeUTF8))
        self.antiAliasing.setItemText(0, QtGui.QApplication.translate("Form", "off", None, QtGui.QApplication.UnicodeUTF8))
        self.antiAliasing.setItemText(1, QtGui.QApplication.translate("Form", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.antiAliasing.setItemText(2, QtGui.QApplication.translate("Form", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.antiAliasing.setItemText(3, QtGui.QApplication.translate("Form", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.antiAliasing.setItemText(4, QtGui.QApplication.translate("Form", "16", None, QtGui.QApplication.UnicodeUTF8))
        self.playButton.setText(QtGui.QApplication.translate("Form", "Play", None, QtGui.QApplication.UnicodeUTF8))
        self.quitButton.setText(QtGui.QApplication.translate("Form", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.fullscreen.setText(QtGui.QApplication.translate("Form", "Fullscreen", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Form = QtGui.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

