# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Launcher.ui'
#
# Created: Wed Oct 02 15:32:23 2013
#      by: PyQt4 UI code generator 4.9.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(500, 430)
        MainWindow.setMinimumSize(QtCore.QSize(500, 430))
        MainWindow.setMaximumSize(QtCore.QSize(500, 430))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../data/images/icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setTabShape(QtGui.QTabWidget.Rounded)
        self.mainWidget = QtGui.QWidget(MainWindow)
        self.mainWidget.setObjectName(_fromUtf8("mainWidget"))
        self.verticalLayout_17 = QtGui.QVBoxLayout(self.mainWidget)
        self.verticalLayout_17.setSpacing(6)
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 6)
        self.verticalLayout_17.setObjectName(_fromUtf8("verticalLayout_17"))
        self.verticalLayout_16 = QtGui.QVBoxLayout()
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.splash = QtGui.QLabel(self.mainWidget)
        self.splash.setEnabled(True)
        self.splash.setMinimumSize(QtCore.QSize(5, 0))
        self.splash.setMaximumSize(QtCore.QSize(500, 16777215))
        self.splash.setText(_fromUtf8(""))
        self.splash.setPixmap(QtGui.QPixmap(_fromUtf8("../data/images/splash.png")))
        self.splash.setObjectName(_fromUtf8("splash"))
        self.verticalLayout_16.addWidget(self.splash)
        self.verticalLayout_18 = QtGui.QVBoxLayout()
        self.verticalLayout_18.setContentsMargins(5, 0, 5, -1)
        self.verticalLayout_18.setObjectName(_fromUtf8("verticalLayout_18"))
        self.line = QtGui.QFrame(self.mainWidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_18.addWidget(self.line)
        self.verticalLayout_16.addLayout(self.verticalLayout_18)
        self.verticalLayout_17.addLayout(self.verticalLayout_16)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_17.addItem(spacerItem)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.verticalLayout_13 = QtGui.QVBoxLayout()
        self.verticalLayout_13.setSpacing(6)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.labelResolution = QtGui.QLabel(self.mainWidget)
        self.labelResolution.setMaximumSize(QtCore.QSize(16777215, 20))
        self.labelResolution.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelResolution.setObjectName(_fromUtf8("labelResolution"))
        self.verticalLayout_13.addWidget(self.labelResolution)
        self.labelAntiAliasing = QtGui.QLabel(self.mainWidget)
        self.labelAntiAliasing.setMaximumSize(QtCore.QSize(16777215, 20))
        self.labelAntiAliasing.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelAntiAliasing.setObjectName(_fromUtf8("labelAntiAliasing"))
        self.verticalLayout_13.addWidget(self.labelAntiAliasing)
        self.labelHidden_10 = QtGui.QLabel(self.mainWidget)
        self.labelHidden_10.setMaximumSize(QtCore.QSize(16777215, 23))
        self.labelHidden_10.setText(_fromUtf8(""))
        self.labelHidden_10.setObjectName(_fromUtf8("labelHidden_10"))
        self.verticalLayout_13.addWidget(self.labelHidden_10)
        self.horizontalLayout_7.addLayout(self.verticalLayout_13)
        self.verticalLayout_14 = QtGui.QVBoxLayout()
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.resolution = QtGui.QComboBox(self.mainWidget)
        self.resolution.setMinimumSize(QtCore.QSize(0, 20))
        self.resolution.setObjectName(_fromUtf8("resolution"))
        self.verticalLayout_14.addWidget(self.resolution)
        self.antiAliasing = QtGui.QComboBox(self.mainWidget)
        self.antiAliasing.setMinimumSize(QtCore.QSize(0, 20))
        self.antiAliasing.setObjectName(_fromUtf8("antiAliasing"))
        self.antiAliasing.addItem(_fromUtf8(""))
        self.antiAliasing.addItem(_fromUtf8(""))
        self.antiAliasing.addItem(_fromUtf8(""))
        self.antiAliasing.addItem(_fromUtf8(""))
        self.antiAliasing.addItem(_fromUtf8(""))
        self.verticalLayout_14.addWidget(self.antiAliasing)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.playButton = QtGui.QPushButton(self.mainWidget)
        self.playButton.setMinimumSize(QtCore.QSize(0, 0))
        self.playButton.setMaximumSize(QtCore.QSize(16777215, 23))
        self.playButton.setObjectName(_fromUtf8("playButton"))
        self.horizontalLayout_8.addWidget(self.playButton)
        self.quitButton = QtGui.QPushButton(self.mainWidget)
        self.quitButton.setMaximumSize(QtCore.QSize(16777215, 23))
        self.quitButton.setObjectName(_fromUtf8("quitButton"))
        self.horizontalLayout_8.addWidget(self.quitButton)
        self.verticalLayout_14.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_7.addLayout(self.verticalLayout_14)
        self.verticalLayout_15 = QtGui.QVBoxLayout()
        self.verticalLayout_15.setSpacing(6)
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.fullscreen = QtGui.QCheckBox(self.mainWidget)
        self.fullscreen.setMinimumSize(QtCore.QSize(0, 20))
        self.fullscreen.setMaximumSize(QtCore.QSize(16777215, 20))
        self.fullscreen.setObjectName(_fromUtf8("fullscreen"))
        self.verticalLayout_15.addWidget(self.fullscreen)
        self.labelHidden_11 = QtGui.QLabel(self.mainWidget)
        self.labelHidden_11.setMaximumSize(QtCore.QSize(16777215, 23))
        self.labelHidden_11.setText(_fromUtf8(""))
        self.labelHidden_11.setObjectName(_fromUtf8("labelHidden_11"))
        self.verticalLayout_15.addWidget(self.labelHidden_11)
        self.labelHidden_12 = QtGui.QLabel(self.mainWidget)
        self.labelHidden_12.setMaximumSize(QtCore.QSize(16777215, 23))
        self.labelHidden_12.setText(_fromUtf8(""))
        self.labelHidden_12.setObjectName(_fromUtf8("labelHidden_12"))
        self.verticalLayout_15.addWidget(self.labelHidden_12)
        self.horizontalLayout_7.addLayout(self.verticalLayout_15)
        self.verticalLayout_17.addLayout(self.horizontalLayout_7)
        MainWindow.setCentralWidget(self.mainWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "BGE Launcher", None, QtGui.QApplication.UnicodeUTF8))
        self.labelResolution.setText(QtGui.QApplication.translate("MainWindow", "Resolution", None, QtGui.QApplication.UnicodeUTF8))
        self.labelAntiAliasing.setText(QtGui.QApplication.translate("MainWindow", "Anti-Aliasing", None, QtGui.QApplication.UnicodeUTF8))
        self.antiAliasing.setItemText(0, QtGui.QApplication.translate("MainWindow", "off", None, QtGui.QApplication.UnicodeUTF8))
        self.antiAliasing.setItemText(1, QtGui.QApplication.translate("MainWindow", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.antiAliasing.setItemText(2, QtGui.QApplication.translate("MainWindow", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.antiAliasing.setItemText(3, QtGui.QApplication.translate("MainWindow", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.antiAliasing.setItemText(4, QtGui.QApplication.translate("MainWindow", "16", None, QtGui.QApplication.UnicodeUTF8))
        self.playButton.setText(QtGui.QApplication.translate("MainWindow", "Play", None, QtGui.QApplication.UnicodeUTF8))
        self.quitButton.setText(QtGui.QApplication.translate("MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.fullscreen.setText(QtGui.QApplication.translate("MainWindow", "Fullscreen", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

